## traefik.toml

[entryPoints]

  [entryPoints.http]  
     address = ":80"

  [entryPoints.traefik]
     address = ":8080"
  
[providers]
  [providers.docker]
  [providers.file]
      filename = "/etc/traefik/dynamic.toml"

[api]
  insecure = true
  dashboard = true
         
