version: '2.3'

services:
  API:
    image: blueswen/api-framework:v1.0.0
    container_name: test_api
    restart: always
    environment:
      - FLASK_CONFIG=${FLASK_CONFIG}
    # env_file:
    #   - ${FLASK_CONFIG}.env
    # ports:
    #   - "${API_PORT}:80"
    volumes:
      - ../../:/root/flask
      - ${MOUNT_ROOT}/${HOSTNAME}/back_file/:/root/flask/back_file/
      - ${MOUNT_ROOT}/${HOSTNAME}/log/:/root/flask/log/
    command: echo "gunicorn -w 1 -k sync --timeout 300 --log-level $${GUNICORN_LOG_LEVEL} -b 0.0.0.0:6001 --chdir /root/flask app:app"
    cpus: '4'
    mem_limit: 2G
